{
 "testCollection": {
  "name": "15.3.4.3_Function.prototype.apply",
  "numTests": 50,
  "tests": [
   {
    "section": "15.3.4.3",
    "description": "Checking if varying the Function.prototype.apply.length property fails",
    "test": "//CHECK#1\nif (!(Function.prototype.apply.hasOwnProperty('length'))) {\n  $FAIL('#1: the Function.prototype.apply has length property.');\n}\n\nvar obj = Function.prototype.apply.length;\n\nFunction.prototype.apply.length = function(){return \"shifted\";};\n\n//CHECK#2\nif (Function.prototype.apply.length !== obj) {\n  $ERROR('#2: the Function.prototype.apply length property has the attributes ReadOnly.');\n}\n",
    "id": "S15.3.4.3_A10"
   },
   {
    "section": "15.3.4.3",
    "description": "TChecking if enumerating the Function.prototype.apply.length property fails",
    "test": "//CHECK#0\nif (!(Function.prototype.apply.hasOwnProperty('length'))) {\n  $FAIL('#0: the Function.prototype.apply has length property.');\n}\n\n\n// CHECK#1\nif (Function.prototype.apply.propertyIsEnumerable('length')) {\n  $ERROR('#1: the Function.prototype.apply.length property has the attributes DontEnum');\n}\n\n// CHECK#2\nfor (var p in Function.prototype.apply){\n  if (p===\"length\")\n      $ERROR('#2: the Function.prototype.apply.length property has the attributes DontEnum');\n}\n",
    "id": "S15.3.4.3_A11"
   },
   {
    "section": "15.3.4.3, 13.2",
    "description": "Checking if obtaining the prototype property of Function.prototype.apply fails",
    "test": "//CHECK#1\nif (Function.prototype.apply.prototype !== undefined) {\n  $ERROR('#1: Function.prototype.apply has not prototype property'+Function.prototype.apply.prototype);\n}\n",
    "id": "S15.3.4.3_A12"
   },
   {
    "section": "15.3.4.3",
    "negative": "TypeError",
    "test": "Function.prototype.apply.call(undefined, {}, []);\n",
    "id": "S15.3.4.3_A13",
    "description": "If IsCallable(func) is false, then throw a TypeError exception."
   },
   {
    "section": "15.3.4.3",
    "negative": "TypeError",
    "test": "Function.prototype.apply.call(null, {}, []);\n",
    "id": "S15.3.4.3_A14",
    "description": "If IsCallable(func) is false, then throw a TypeError exception."
   },
   {
    "section": "15.3.4.3",
    "negative": "TypeError",
    "test": "Function.prototype.apply.call({}, {}, []);\n",
    "id": "S15.3.4.3_A15",
    "description": "If IsCallable(func) is false, then throw a TypeError exception."
   },
   {
    "section": "15.3.4.3",
    "description": "A RegExp is not a function, but it may be callable. Iff it is, it's typeof should be 'function', in which case apply should accept it as a valid this value.",
    "test": "var re = (/x/);\nif (typeof re === 'function') {\n  Function.prototype.apply.call(re, undefined, ['x']);\n} else {\n  try {\n    Function.prototype.bind.call(re, undefined);\n    $FAIL('#1: If IsCallable(func) is false, ' +\n          'then (bind should) throw a TypeError exception');\n  } catch (e) {\n    if (!(e instanceof TypeError)) {\n      $ERROR('#1: TypeError expected. Actual: ' + e);\n    }\n  }\n}\n",
    "id": "S15.3.4.3_A16"
   },
   {
    "section": "15.3.4.3",
    "description": "Calling \"apply\" method of the object that does not have a [[Call]] property.\nPrototype of the object is Function()",
    "test": "var proto=Function();\n\nfunction FACTORY(){};\n\nFACTORY.prototype=proto;\n\nvar obj = new FACTORY;\n\n//CHECK#1\nif (typeof obj.apply !== \"function\") {\n  $ERROR('#1: apply method accessed');\n}\n\n//CHECK#2\ntry {\n  obj.apply();\n  $FAIL('#2: If the object does not have a [[Call]] property, a TypeError exception is thrown');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#2.1: If the object does not have a [[Call]] property, a TypeError exception is thrown');\n  }\n}\n",
    "id": "S15.3.4.3_A1_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "Calling \"apply\" method of the object that does not have a [[Call]] property.\nPrototype of the object is Function.prototype",
    "test": "function FACTORY(){};\n\nFACTORY.prototype=Function.prototype;\n\nvar obj = new FACTORY;\n\n//CHECK#1\nif (typeof obj.apply !== \"function\") {\n  $ERROR('#1: apply method accessed');\n}\n\n//CHECK#2\ntry {\n  obj.apply();\n  $FAIL('#2: If the object does not have a [[Call]] property, a TypeError exception is thrown');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#2.1: If the object does not have a [[Call]] property, a TypeError exception is thrown');\n  }\n}\n",
    "id": "S15.3.4.3_A1_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking Function.prototype.apply.length",
    "test": "//CHECK#1\nif (typeof Function.prototype.apply !== \"function\") {\n  $ERROR('#1: apply method defined');\n}\n\n//CHECK#2\nif (typeof Function.prototype.apply.length === \"undefined\") {\n  $ERROR('#2: length property of apply method defined');\n}\n\n//CHECK#3\nif (Function.prototype.apply.length !== 2) {\n  $ERROR('#3: The length property of the apply method is 2');\n}\n",
    "id": "S15.3.4.3_A2_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking f.apply.length, where f is new Function",
    "test": "var f=new Function;\n\n//CHECK#1\nif (typeof f.apply !== \"function\") {\n  $ERROR('#1: apply method accessed');\n}\n\n//CHECK#2\nif (typeof f.apply.length === \"undefined\") {\n  $ERROR('#2: length property of apply method defined');\n}\n\n//CHECK#3\nif (f.apply.length !== 2) {\n  $ERROR('#3: The length property of the apply method is 2');\n}\n",
    "id": "S15.3.4.3_A2_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "Not any arguments at apply function",
    "test": "Function(\"this.field=\\\"strawberry\\\"\").apply();\n\n//CHECK#1\nif (this[\"field\"] !== \"strawberry\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking by using eval, no any arguments at apply function",
    "test": "eval(\" (function(){this.feat=1}).apply()\");\n\n//CHECK#1\nif (this[\"feat\"] !== 1) {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T10"
   },
   {
    "section": "15.3.4.3",
    "description": "Argument at apply function is null",
    "test": "Function(\"this.field=\\\"green\\\"\").apply(null);\n\n//CHECK#1\nif (this[\"field\"] !== \"green\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "Argument at apply function is void 0",
    "test": "Function(\"this.field=\\\"battle\\\"\").apply(void 0);\n\n//CHECK#1\nif (this[\"field\"] !== \"battle\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T3"
   },
   {
    "section": "15.3.4.3",
    "description": "Argument at apply function is undefined",
    "test": "Function(\"this.field=\\\"oil\\\"\").apply(undefined);\n\n//CHECK#1\nif (this[\"field\"] !== \"oil\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T4"
   },
   {
    "section": "15.3.4.3",
    "description": "No any arguments at apply function and it called inside function declaration",
    "test": "function FACTORY(){\n  Function(\"this.feat=\\\"in da haus\\\"\").apply();\n};\n\nvar obj = new FACTORY;\n\n//CHECK#1\nif (this[\"feat\"] !== \"in da haus\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n\n//CHECK#2\nif (typeof obj.feat !== \"undefined\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T5"
   },
   {
    "section": "15.3.4.3",
    "description": "Argument at apply function is null and it called inside function declaration",
    "test": "function FACTORY(){\n  (function(){this.feat=\"kamon beyba\"}).apply(null);\n};\n\nvar obj = new FACTORY;\n\n//CHECK#1\nif (this[\"feat\"] !== \"kamon beyba\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n\n//CHECK#2\nif (typeof obj.feat !== \"undefined\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T6"
   },
   {
    "section": "15.3.4.3",
    "description": "Argument at apply function is void 0 and it called inside function declaration",
    "test": "(function FACTORY(){\n  Function(\"this.feat=\\\"in da haus\\\"\").apply(void 0);\n})();\n\n\n//CHECK#1\nif (this[\"feat\"] !== \"in da haus\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T7"
   },
   {
    "section": "15.3.4.3",
    "description": "Argument at apply function is undefined and it called inside function declaration",
    "test": "(function FACTORY(){\n  (function(){this.feat=\"kamon beyba\"}).apply(undefined);\n})();\n\n//CHECK#1\nif (this[\"feat\"] !== \"kamon beyba\") {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T8"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking by using eval, argument at apply function is void 0",
    "test": "eval( \" Function(\\\"this.feat=1\\\").apply(void 0) \" );\n\n//CHECK#1\nif (this[\"feat\"] !== 1) {\n  $ERROR('#1: If thisArg is null or undefined, the called function is passed the global object as the this value');\n}\n",
    "id": "S15.3.4.3_A3_T9"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is number",
    "test": "var obj=1;\n\nvar retobj = Function(\"this.touched= true; return this;\").apply(obj);\n\n//CHECK#1\nif (typeof obj.touched !== \"undefined\") {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n//CHECK#2\nif (!(retobj[\"touched\"])) {\n  $ERROR('#2: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}",
    "id": "S15.3.4.3_A5_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is boolean true",
    "test": "var obj=true;\n\nvar retobj = new Function(\"this.touched= true; return this;\").apply(obj);\n\n//CHECK#1\nif (typeof obj.touched !== \"undefined\") {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n//CHECK#2\nif (!(retobj[\"touched\"])) {\n  $ERROR('#2: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n",
    "id": "S15.3.4.3_A5_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is string",
    "test": "var obj=\"soap\";\n\nvar retobj = ( function(){this.touched= true; return this;} ).apply(obj);\n\n//CHECK#1\nif (typeof obj.touched !== \"undefined\") {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n//CHECK#2\nif (!(retobj[\"touched\"])) {\n  $ERROR('#2: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n",
    "id": "S15.3.4.3_A5_T3"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is function variable that return this",
    "test": "f = function(){this.touched= true; return this;};\n\nretobj = f.apply(obj);\n\n//CHECK#1\nif (typeof obj !== \"undefined\") {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n//CHECK#2\nif (!(retobj[\"touched\"])) {\n  $ERROR('#2: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\nvar obj;\n",
    "id": "S15.3.4.3_A5_T4"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is function variable",
    "test": "var f = function(){this.touched= true;};\n\nvar obj={};\n\nf.apply(obj);\n\n//CHECK#1\nif (!(obj.touched)) {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n",
    "id": "S15.3.4.3_A5_T5"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is new String()",
    "test": "var obj=new String(\"soap\");\n\n( function(){this.touched= true;}).apply(obj);\n\n//CHECK#1\nif (!(obj.touched)) {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n",
    "id": "S15.3.4.3_A5_T6"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is new Number()",
    "test": "var obj=new Number(1);\n\nFunction(\"this.touched= true;\").apply(obj);\n\n//CHECK#1\nif (!(obj.touched)) {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n\n",
    "id": "S15.3.4.3_A5_T7"
   },
   {
    "section": "15.3.4.3",
    "description": "thisArg is Function()",
    "test": "var obj=Function();\n\nnew Function(\"this.touched= true; return this;\").apply(obj);\n\n//CHECK#1\nif (!(obj.touched)) {\n  $ERROR('#1: If thisArg is not null(defined) the called function is passed ToObject(thisArg) as the this value');\n}\n",
    "id": "S15.3.4.3_A5_T8"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (1,{})",
    "test": "//CHECK#1\ntry {\n  Function().apply(1,{});\n  $FAIL('#1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n  }\n}\n",
    "id": "S15.3.4.3_A6_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (null,1)",
    "test": "//CHECK#1\ntry {\n  Function().apply(null,1);\n  $FAIL('#1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n  }\n}\n",
    "id": "S15.3.4.3_A6_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (object,\"1,3,4\")",
    "test": "obj={};\n\n//CHECK#1\ntry {\n  Function().apply(obj,\"1,3,4\");\n  $FAIL('#1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n  }\n}\n",
    "id": "S15.3.4.3_A6_T3"
   },
   {
    "section": "15.3.4.3",
    "description": ": argArray is (this,function(){return arguments;});",
    "test": "//CHECK#1\ntry {\n  Function().apply(this,function(){return arguments;});\n  $FAIL('#1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: if argArray is neither an array nor an arguments object (see 10.1.8), a TypeError exception is thrown');\n  }\n}\n",
    "id": "S15.3.4.3_A6_T4"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (null,[1])",
    "test": "Function(\"a1,a2,a3\",\"this.shifted=a1;\").apply(null,[1]);\n\n//CHECK#1\nif (this[\"shifted\"] !== 1) {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (empty object, arguments), inside function call without declaration used",
    "test": "var obj={};\n\n(function (){\n  Function(\"a1,a2,a3\",\"this.shifted=a1+a2+a3;\").apply(obj,arguments);\n})(\"\",4,2);\n\n//CHECK#1\nif (obj[\"shifted\"] !== \"42\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n//CHECK#2\nif (typeof this[\"shifted\"] !== \"undefined\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T10"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (null,[1,2,3])",
    "test": "new Function(\"a1,a2\",\"a3\",\"this.shifted=a2;\").apply(null,[1,2,3]);\n\n//CHECK#1\nif (this[\"shifted\"] !== 2) {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (empty object, new Array(\"nine\",\"inch\",\"nails\"))",
    "test": "i=0;\n\np={toString:function(){return \"a\"+(++i);}};\n\nobj={};\n\nFunction(p,\"a2,a3\",\"this.shifted=a1;\").apply(obj, new Array(\"nine\",\"inch\",\"nails\"));\n\n//CHECK#1\nif (obj[\"shifted\"] !== \"nine\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n//CHECK#2\nif (typeof this[\"shifted\"] !== \"undefined\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T3"
   },
   {
    "section": "15.3.4.3",
    "description": ": argArray is (empty object, ( function(){return arguments;}) (\"a\",\"b\",\"c\"));",
    "test": "i=0;\n\np={toString:function(){return \"a\"+(++i);}};\n\nobj={};\n\nnew Function(p,p,p, \"this.shifted=a3;\").apply( obj,( function(){return arguments;}) (\"a\",\"b\",\"c\") );\n\n//CHECK#1\nif (obj[\"shifted\"] !== \"c\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n//CHECK#2\nif (typeof this[\"shifted\"] !== \"undefined\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T4"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (null, arguments), inside function declaration used",
    "test": "function FACTORY(){\n  Function(\"a1,a2,a3\",\"this.shifted=a1+a2+a3;\").apply(null,arguments);\n}\n\nobj=new FACTORY(\"\",1,2);\n\n//CHECK#1\nif (this[\"shifted\"] !== \"12\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n//CHECK#2\nif (typeof obj.shifted !== \"undefined\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T5"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (this, arguments), inside function declaration used",
    "test": "function FACTORY(){\n  Function(\"a1,a2,a3\",\"this.shifted=a1+a2+a3;\").apply(this,arguments);\n}\n\nobj=new FACTORY(\"\",4,2);\n\n//CHECK#1\nif (obj[\"shifted\"] !== \"42\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n//CHECK#2\nif (typeof this[\"shifted\"] !== \"undefined\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T6"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (null, arguments), inside function call without declaration used",
    "test": "(function (){\n  Function(\"a1,a2,a3\",\"this.shifted=a1+a2+a3;\").apply(null,arguments);\n})(\"\",1,2);\n\n//CHECK#1\nif (this[\"shifted\"] !== \"12\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n",
    "id": "S15.3.4.3_A7_T7"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (this, arguments), inside function call without declaration used",
    "test": "(function (){\n  Function(\"a1,a2,a3\",\"this.shifted=a1+a2+a3;\").apply(this,arguments);\n})(\"\",4,2);\n\n//CHECK#2\nif (this[\"shifted\"] !== \"42\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T8"
   },
   {
    "section": "15.3.4.3",
    "description": "argArray is (empty object, arguments), inside function declaration used",
    "test": "function FACTORY(){\n  var obj = {};\n  Function(\"a1,a2,a3\",\"this.shifted=a1+a2+a3;\").apply(obj,arguments);\n  return obj;\n}\n\nobj=new FACTORY(\"\",1,2);\n\n//CHECK#1\nif (typeof this[\"shifted\"] !== \"undefined\") {\n  $ERROR('#1: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n//CHECK#2\nif (obj.shifted !== \"12\") {\n  $ERROR('#2: If argArray is either an array or an arguments object, the function is passed the...');\n}\n\n",
    "id": "S15.3.4.3_A7_T9"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking if creating \"new Function.prototype.apply\" fails",
    "test": "try {\n  obj = new Function.prototype.apply;\n  $ERROR('#1: Function.prototype.apply can\\'t be used as [[create]] caller');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: Function.prototype.apply can\\'t be used as [[create]] caller');\n  }\n}\n",
    "id": "S15.3.4.3_A8_T1"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking if creating \"new Function.prototype.apply()\" fails",
    "test": "try {\n  obj = new Function.prototype.apply();\n  $ERROR('#1: Function.prototype.apply can\\'t be used as [[create]] caller');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: Function.prototype.apply can\\'t be used as [[create]] caller');\n  }\n}\n",
    "id": "S15.3.4.3_A8_T2"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking if creating \"new Function.apply\" fails",
    "test": "try {\n  obj = new Function.apply;\n  $ERROR('#1: Function.prototype.apply can\\'t be used as [[create]] caller');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: Function.prototype.apply can\\'t be used as [[create]] caller');\n  }\n}\n",
    "id": "S15.3.4.3_A8_T3"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking if creating \"new (Function(\"this.p1=1\").apply)\" fails",
    "test": "try {\n  obj = new (Function(\"this.p1=1\").apply);\n  $ERROR('#1: Function.prototype.apply can\\'t be used as [[create]] caller');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: Function.prototype.apply can\\'t be used as [[create]] caller');\n  }\n}\n",
    "id": "S15.3.4.3_A8_T4"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking if creating \"new Function(\"this.p1=1\").apply\" fails",
    "test": "try {\n  FACTORY = Function(\"this.p1=1\").apply;\n  obj = new FACTORY();\n  $ERROR('#1: Function.prototype.apply can\\'t be used as [[create]] caller');\n} catch (e) {\n  if (!(e instanceof TypeError)) {\n  \t$ERROR('#1.1: Function.prototype.apply can\\'t be used as [[create]] caller');\n  }\n}\n",
    "id": "S15.3.4.3_A8_T5"
   },
   {
    "section": "15.3.4.3",
    "description": ": Checking if creating \"new (Function(\"function f(){this.p1=1;};return f\").apply())\" fails;",
    "test": "//CHECK#1\ntry {\n  obj = new (Function(\"function f(){this.p1=1;};return f\").apply());\n} catch (e) {\n  $ERROR('#1: Function.prototype.apply can\\'t be used as [[create]] caller');\n}\n\n//CHECK#2\nif (obj.p1!== 1) {\n  $ERROR('#2: Function.prototype.apply can\\'t be used as [[create]] caller');\n}\n",
    "id": "S15.3.4.3_A8_T6"
   },
   {
    "section": "15.3.4.3",
    "description": "Checking if deleting the Function.prototype.apply.length property fails",
    "test": "//CHECK#0\nif (!(Function.prototype.apply.hasOwnProperty('length'))) {\n  $FAIL('#0: the Function.prototype.apply has length property');\n}\n\n//CHECK#1\nif (delete Function.prototype.apply.length) {\n  $ERROR('#1: The Function.prototype.apply.length property has the attributes DontDelete');\n}\n\n//CHECK#2\nif (!(Function.prototype.apply.hasOwnProperty('length'))) {\n  $FAIL('#2: The Function.prototype.apply.length property has the attributes DontDelete');\n}\n",
    "id": "S15.3.4.3_A9"
   }
  ]
 }
}
